apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: data-analytics
spec:
  dnsNames:
    - example.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: data-analytics-tls
