apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playwright-ui
spec:
  dnsNames:
    - example.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: playwright-ui-tls
