resources:
- ./../base
namespace: api

patchesStrategicMerge:
- deploy.yaml

commonLabels:
  app: api

configMapGenerator:
  - name: api
    literals:
      - APP_ENV=stage
      - NODE_ENV=staging
      - API_PORT=3000
      - API_HOST=https://api-staging.nexera.id
      - CMS_PUBLIC_URL=https://cms-staging.nexera.id

secretGenerator:
  - name: api
    envs:
      - .env

patches:
- target:
    kind: Ingress
    name: api
  path: ./ingress-json-patch.yaml
- target:
    kind: Certificate
    name: api
  path: ./cert-json-patch.yaml
