apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zk-verifier
spec:
  dnsNames:
  - example.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: zk-verifier-tls
