apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitest-ui
spec:
  template:
    spec:
      containers:
        - name: vitest-ui
          envFrom:
            - configMapRef:
                name: vitest-ui
            - secretRef:
                name: vitest-ui
