# Default values for openmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/openmeterio/openmeter
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  port: 8888

ingress:
  enabled: true
  className: "nginx"
  annotations:
    external-dns: private
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: ${OPEN_METER_URL}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - ${OPEN_METER_URL}
      secretName: openmeter-tls

cert:
  enabled: true
  annotations: {}
  issuer: letsencrypt-prod
  secretName: openmeter-tls
  dnsNames:
    - ${OPEN_METER_URL}

resources:
  {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  meters:
    []
