{{- if .Values.cert.enabled -}}
{{- $fullName := include "openmeter.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "openmeter.labels" . | nindent 4 }}
  {{- with .Values.cert.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  dnsNames:
    {{- range .Values.cert.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.cert.issuer }}
  secretName: {{ .Values.cert.secretName }}
{{- end }}
