apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-ui
spec:
  template:
    spec:
      containers:
        - name: playwright-ui
          envFrom:
            - configMapRef:
                name: playwright-ui
            - secretRef:
                name: playwright-ui
