name: Auto Merge

on:
  pull_request:
    branches:
      - main
      - staging
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    branches:
      - main
      - staging
    types:
      - submitted
  check_suite:
    branches:
      - main
      - staging
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Check for all current approvals if they match with appropriate GH team
      - name: Checking for PR permissions
        id: check_pr_permissions
        shell: bash
        run: |
          exit 1

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Enable merge commits
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.BOT_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/MFX-com/testing-packages \
            -d '{"allow_merge_commit":true}' \
            --output /dev/null

      - name: Automatic merge
        id: auto-merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          MERGE_METHOD: merge
          LOG: DEBUG

      - name: Disable merge commits
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.BOT_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/MFX-com/testing-packages \
            -d '{"allow_merge_commit":false}' \
            --output /dev/null
