name: autoupdate

on:
  pull_request:
    branches:
      - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DRY_RUN: "false"
          PR_FILTER: "all"
          EXCLUDED_LABELS: "dependencies,wontfix,renovate-bot"
          MERGE_MSG: "Branch was auto-updated."
          PR_READY_STATE: "ready_for_review"
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"
