name: autoupdate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autoupdate:
    name: Update with base branch
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Merge base branch
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ steps.generate_token.outputs.token }}'
          DRY_RUN: "false"
          PR_FILTER: "all"
          EXCLUDED_LABELS: "dependencies,wontfix,renovate-bot"
          MERGE_MSG: "Branch was auto-updated."
          PR_READY_STATE: "ready_for_review"
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "ignore"

      - name: Merge conflicts found
        if: ${{ steps.autoupdate.outputs.conflicted }}
        shell: bash
        run: |
          echo "test 1"

      - name: No merge conflicts found
        if: ${{ !steps.autoupdate.outputs.conflicted }}
        shell: bash
        run: |
          echo "test 2"