name: Build and deploy docker images

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    name: Deploy the docker images
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request number
        run: |
          echo The PR ${{ github.event.pull_request.number }} was merged!

      - name: Get SHA
        run: |
          echo GitHub SHA: ${{ github.sha }}

      - name: Show target branch name
        run: |
          echo Base branch name: ${{ github.event.pull_request.base.ref }}
          echo Head branch name: ${{ github.event.pull_request.head.ref }}
