name: Create pull request

on:
  workflow_dispatch:
    inputs:
      source_branch:
        type: choice
        description: Source branch
        options:
          - development
          - staging
        default: development
      target_branch:
        type: choice
        description: Target branch
        options:
          - staging
          - main
        default: staging

jobs:
  create-pull-request:
    name: Create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Validate parameters
        shell: bash
        run: |
          if [ ${{ inputs.source_branch }} == 'staging' ] && [ ${{ inputs.target_branch }} == 'staging' ]; then
            exit 1
          elif [ ${{ inputs.source_branch }} == 'development' ] && [ ${{ inputs.target_branch }} == 'main' ]; then
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ inputs.source_branch }}
          target_branch: ${{ inputs.target_branch }}
          title: ${{ inputs.source_branch }} to ${{ inputs.target_branch }}
          body: "**Automated pull request**"
          assignee: markoftw
          label: automerge,${{ inputs.target_branch == 'staging' && 'STAGING' || 'PRODUCTION' }}
          draft: false
          ignore_users: "dependabot"
