name: Build SECOND docker image

on:
  pull_request:
    branches:
      - main
      - staging
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-second
  cancel-in-progress: true

env:
  SECOND_IMAGE: "ghcr.io/mfx-com/testing-packages/apps/second-app"
  NODE_VERSION: 18.17.0
  PNPM_VERSION: 8.7.5

jobs:
  prepare-environment:
    name: Prepare environment for second image
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Get pull request number
        run: |
          echo The PR ${{ github.event.pull_request.number }} was updated!

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

#      - uses: jpribyl/action-docker-layer-caching@v0.1.1
#        # Ignore the failure of a step and avoid terminating the job.
#        continue-on-error: true
#        with:
#          key: second-docker-cache-${{ github.event.pull_request.number }}
#          restore-keys: |
#            second-docker-cache-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull docker layers
        continue-on-error: true
        run: |
          docker pull ${{ env.SECOND_IMAGE }}:${{ github.event.pull_request.number }}-${{ steps.extract_branch.outputs.branch }}

      - name: Run docker build SECOND
        run: |
          pnpm run docker:second -t ${{ env.SECOND_IMAGE }}:${{ github.event.pull_request.number }}-${{ steps.extract_branch.outputs.branch }}

      - name: Push docker images
        run: |
          docker push ${{ env.SECOND_IMAGE }}:${{ github.event.pull_request.number }}-${{ steps.extract_branch.outputs.branch }}
