name: Release

on:
  pull_request:
    types: [ closed ]
    branches:
      - mainz

  push:
    branches:
      - mainz

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.7.5
          run_install: true

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
#          publish: pnpm release
          commit: "ci(changesets): version packages"

#      - name: Testing changeset
#        shell: bash
#        run: |
#          npx changeset
#
#      - name: Testing versions
#        shell: bash
#        run: |
#          npx changeset version
