name: PR Agent

on:
  pull_request:

jobs:
  pr_agent_job:
    name: Run PR agent on every pull request, respond to user comments
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: PR Agent action step (label)
        if: ${{ github.event.pull_request.base.ref == 'main' && contains(github.event.pull_request.labels.*.name, 'ready for review') }}
        id: pragent
        uses: Codium-ai/pr-agent@main
        # Additional options https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.ORG: "MareFX"
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 20 # Increase number of code suggestions, default: 5

      - name: PR Agent action step (comment)
        if: ${{ github.event.pull_request.base.ref == 'main' && contains(github.event.comment.body, 'run agent') }}
        id: pragent_comment
        uses: Codium-ai/pr-agent@main
        # Additional options https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.ORG: "MareFX"
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 20 # Increase number of code suggestions, default: 5
